// docs/react/src/components/page/index.tsx
import { VirtualList, type VirtualizerInstance } from '@z-cloud/virtual-react';
import { useRef } from 'react';

export default function VirtualListWithPageScroll() {
  const instanceRef = useRef<VirtualizerInstance>(null);

  return (
    <div>
      <div className="demo-btns">
        <button
          onClick={() =>
            instanceRef.current?.scrollToIndex(2000, { behavior: 'smooth' })
          }
        >
          scrollToIndex(2000) with smooth
        </button>
        <button
          onClick={() =>
            instanceRef.current?.scrollToIndex(3000, { align: 'center' })
          }
        >
          scrollToIndex(3000) with align center
        </button>
        <button
          onClick={() => instanceRef.current?.scrollToOffset(3000, 'smooth')}
        >
          scrollToOffset(3000) with smooth
        </button>
      </div>
      <VirtualList
        itemClassName="demo-list-item"
        count={10000}
        size={(index) => (index % 2 === 0 ? 60 : 120)}
        followPageScroll
        overscan={5}
        onReady={(virtualizer) => {
          instanceRef.current = virtualizer;
        }}
      >
        {({ index }) => (
          <div className={index % 2 ? 'demo-list-odd' : 'demo-list-even'}>
            第 {index} 行
          </div>
        )}
      </VirtualList>
    </div>
  );
}

// docs/vue/docs/components/page/index.vue
<script setup lang="ts">
import { VirtualList } from '@z-cloud/virtual-vue'
import { randomSize, randomColors } from '../../utils'
</script>

<template>
  <div>
    <VirtualList
      itemClassName="demo-list-item"
      followPageScroll
      :overscan="4"
      :size="() => randomSize() + 80"
      :count="10000"
      :lanes="2"
      :gap="8"
    >
      <template #default="{ index }">
        <div
          :style="{ backgroundColor: randomColors[index % randomColors.length] }"
          :class="index % 2 ? 'demo-list-odd' : 'demo-list-even'"
        />
      </template>
    </VirtualList>
  </div>
</template>
