// docs/vue/docs/components/basic/grid.vue
<script setup lang="ts">
import { type VirtualizerInstance, VirtualList } from '@z-cloud/virtual-vue'
import { ref } from 'vue'

const instanceRef = ref<VirtualizerInstance>()

const onReady = (virtualizer: VirtualizerInstance) => {
  instanceRef.value = virtualizer
}
</script>

<template>
  <div>
    <div className="demo-btns">
      <button @click="instanceRef?.scrollToIndex(3000, { align: 'center' })">
        scrollToIndex(3000) with align center
      </button>
      <button @click="instanceRef?.scrollToOffset(4000)">scrollToOffset(4000)</button>
    </div>
    <VirtualList
      itemClassName="demo-list-item"
      style="height: 400px; width: 400px; font-size: 14px"
      :count="5000"
      :size="60"
      grid
      :gridSize="[100, 40]"
      :gap="10"
      :overscan="5"
      @ready="onReady"
    >
      <template #default="{ rowItem, colItem }">
        <div :class="rowItem.index % 2 ? 'demo-list-odd' : 'demo-list-even'">
          cell {{ rowItem.index }} {{ colItem.index }}
        </div>
      </template>
    </VirtualList>
  </div>
</template>

// docs/react/src/components/basic/grid.tsx
import { VirtualList, type VirtualizerInstance } from '@z-cloud/virtual-react';
import { useRef } from 'react';

export default function GridVirtualList() {
  const instanceRef = useRef<VirtualizerInstance>(null);

  return (
    <div>
      <div className="demo-btns">
        <button
          onClick={() =>
            instanceRef.current?.scrollToIndex(2000, { behavior: 'instant' })
          }
        >
          scrollToIndex(2000)
        </button>
        <button
          onClick={() =>
            instanceRef.current?.scrollToIndex(3000, { align: 'center' })
          }
        >
          scrollToIndex(3000) with align center
        </button>
      </div>
      <VirtualList
        style={{ height: 400, width: 600 }}
        itemClassName="demo-list-item"
        count={10000}
        size={60}
        grid
        gridSize={[80, 40]}
        gap={10}
        overscan={5}
        onReady={(virtualizer) => {
          instanceRef.current = virtualizer;
        }}
      >
        {({ index }, colItem) => (
          <div className={index % 2 ? 'demo-list-odd' : 'demo-list-even'}>
            cell {index} {colItem?.index}
          </div>
        )}
      </VirtualList>
    </div>
  );
}
