// packages/pull-to-refresh/src/vue/refresh.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch, useCssModule } from 'vue'
import { usePullToRefresh } from './hooks/use-pull-to-refresh'
import { PullToRefreshProps } from './typings'
import { useEventBind } from './hooks/use-event-bind'

const props = withDefaults(defineProps<PullToRefreshProps>(), {
  local: false,
})

const classes = useCssModule('classes')

defineEmits(['refresh'])

const refreshDomRef = ref<HTMLElement | null>(null)

const instance = usePullToRefresh(props)
useEventBind(instance.value, props.local ? refreshDomRef : void 0)

const arcProgress = computed(() =>
  Math.min(Math.max(0, instance.value.pullDistance) / instance.value.options.maxPullDistance, 1),
)

const opacity = computed(() => {
  return ['finished', 'initial'].includes(instance.value.status)
    ? '0'
    : `${Math.min(0.6 + arcProgress.value, 1)}`
})

const onTransitionEnd = () => {
  if (instance.value.status === 'finished') {
    instance.value.reset()
  }
}

onMounted(() => {
  if (!props.local) {
    document.body.classList.add(classes.hasPullToRefresh!)
  }
})

watch(
  () => instance.value.status,
  (status) => {
    document.body.classList.toggle(classes.pullToRefreshPulling!, status === 'pulling')
  },
)

onUnmounted(() => {
  if (!props.local) {
    document.body.classList.remove(classes.hasPullToRefresh!)
  }
  document.body.classList.remove(classes.pullToRefreshPulling!)
})
</script>

<template>
  <div
    ref="refreshDomRef"
    :class="[classes.refreshWraper, { [classes.pageScroll ?? '']: !local }]"
    :style="
      {
        '--delay': `${instance.status === 'pulling' ? -arcProgress : 0}s`,
        transform: `translate(-50%, ${instance.pullDistance}px) scale(${
          instance.status === 'finished' ? 0.4 : 1
        })`,
        opacity,
      } as React.CSSProperties & Record<string, string>
    "
    @transitionend="onTransitionEnd"
  >
    <svg
      :class="classes.indicator"
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
    >
      <circle
        cx="12"
        cy="12"
        r="10"
        fill="none"
        :class="[classes.circle, classes[instance.status]]"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
    </svg>
  </div>
</template>

<style module="classes">
@import url(../styles/index.module.css);
</style>

// packages/pull-to-refresh/src/react/refresh.tsx
import { useIsomorphicLayoutEffect, usePullToRefresh } from './hooks/use-pull-to-refresh'
import type { PullToRefreshProps } from './typings'
import classes from '../styles/index.module.css'
import { classnames } from '../lib/utils'
import { useRef } from 'react'
import { useEventBind } from './hooks/use-event-bind'

export function PullToRefresh({
  style,
  local = false,
  className,
  ...restProps
}: PullToRefreshProps) {
  const refreshDomRef = useRef<HTMLDivElement>(null)
  const instance = usePullToRefresh(restProps)
  useEventBind(instance, local ? refreshDomRef : void 0)

  const arcProgress = Math.min(
    Math.max(0, instance.pullDistance) / instance.options.maxPullDistance,
    1,
  )
  const opacity = ['finished', 'initial'].includes(instance.status)
    ? '0'
    : `${Math.min(0.6 + arcProgress, 1)}`

  useIsomorphicLayoutEffect(() => {
    if (!local) {
      document.body.classList.add(classes.hasPullToRefresh!)
    }

    return () => document.body.classList.remove(classes.hasPullToRefresh!)
  }, [])

  useIsomorphicLayoutEffect(() => {
    document.body.classList.toggle(classes.pullToRefreshPulling!, instance.status === 'pulling')

    return () => document.body.classList.remove(classes.pullToRefreshPulling!)
  }, [instance.status])

  return (
    <div
      ref={refreshDomRef}
      style={
        {
          ...style,
          '--delay': `${instance.status === 'pulling' ? -arcProgress : 0}s`,
          transform: `translate(-50%, ${instance.pullDistance}px) scale(${
            instance.status === 'finished' ? 0.4 : 1
          })`,
          opacity,
        } as React.CSSProperties & Record<string, string>
      }
      onTransitionEnd={() => {
        if (instance.status === 'finished') {
          instance.reset()
        }
      }}
      className={classnames(className, classes.refreshWraper, {
        [classes.pageScroll as string]: !local,
      })}
    >
      <svg
        className={classes.indicator}
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
        xmlns="http://www.w3.org/2000/svg"
      >
        <circle
          cx="12"
          cy="12"
          r="10"
          fill="none"
          className={classnames(classes.circle, classes[instance.status])}
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
        />
      </svg>
    </div>
  )
}
