// docs/vue/docs/components/dynamic/horizontal.vue
<script setup lang="ts">
import { type VirtualizerInstance, VirtualList } from '@z-cloud/virtual-vue'
import { ref } from 'vue'

const instanceRef = ref<VirtualizerInstance>()

const dynamicSizes = new Array(10000).fill(true).map(() => Math.round(Math.random() * 80 + 80))

const onReady = (virtualizer: VirtualizerInstance) => {
  instanceRef.value = virtualizer
}
</script>

<template>
  <div>
    <div className="demo-btns">
      <button @click="instanceRef?.scrollToIndex(3000, { align: 'center' })">
        scrollToIndex(3000) with align center
      </button>
      <button @click="instanceRef?.scrollToOffset(4000)">scrollToOffset(4000)</button>
    </div>
    <VirtualList
      itemClassName="demo-list-item"
      horizontal
      style="height: 100px; width: 100%"
      :count="10000"
      :size="100"
      dynamic-size
      @ready="onReady"
    >
      <template #default="{ index }">
        <div :style="{ height: dynamicSizes[index] }" :class="index % 2 ? 'demo-list-odd' : 'demo-list-even'">
          第 {{ index }} 列
        </div>
      </template>
    </VirtualList>
  </div>
</template>

// docs/react/src/components/dynamic/horizontal.tsx
import { VirtualList, type VirtualizerInstance } from '@z-cloud/virtual-react';
import { useRef } from 'react';

const dynamicSizes = new Array(10000)
  .fill(true)
  .map(() => Math.round(Math.random() * 80 + 80));

export default function ColumnDynamicVirtualList() {
  const instanceRef = useRef<VirtualizerInstance>(null);

  return (
    <div>
      <div className="demo-btns">
        <button
          onClick={() =>
            instanceRef.current?.scrollToIndex(3000, { align: 'center' })
          }
        >
          scrollToIndex(3000) with align center
        </button>
      </div>
      <VirtualList
        style={{ height: 100 }}
        itemClassName="demo-list-item"
        count={10000}
        size={100}
        overscan={5}
        horizontal
        dynamicSize
        onReady={(virtualizer) => {
          instanceRef.current = virtualizer;
        }}
      >
        {({ index }) => (
          <div
            style={{ width: dynamicSizes[index] }}
            className={index % 2 ? 'demo-list-odd' : 'demo-list-even'}
          >
            第 {index} 列
          </div>
        )}
      </VirtualList>
    </div>
  );
}
