// docs/vue/docs/components/dynamic/vertical.vue
<script setup lang="ts">
import { type VirtualizerInstance, VirtualList } from '@z-cloud/virtual-vue'
import { ref } from 'vue'

const instanceRef = ref<VirtualizerInstance>()
const dynamicSizes = new Array(10000).fill(true).map(() => Math.round(Math.random() * 80 + 30))

const onReady = (virtualizer: VirtualizerInstance) => {
  instanceRef.value = virtualizer
}
</script>

<template>
  <div>
    <div className="demo-btns">
      <button @click="instanceRef?.scrollToIndex(3000, { align: 'center' })">
        scrollToIndex(3000) with align center
      </button>
      <button @click="instanceRef?.scrollToOffset(4000)">scrollToOffset(4000)</button>
    </div>
    <VirtualList
      itemClassName="demo-list-item"
      dynamic-size
      style="height: 400px"
      :count="10000"
      :size="60"
      @ready="onReady"
    >
      <template #default="{ index }">
        <div :style="{ height: `${dynamicSizes[index]}px` }" :class="index % 2 ? 'demo-list-odd' : 'demo-list-even'">
          第 {{ index }} 行
        </div>
      </template>
    </VirtualList>
  </div>
</template>

// docs/react/src/components/dynamic/vertical.tsx
import { VirtualList, type VirtualizerInstance } from '@z-cloud/virtual-react';
import { useRef } from 'react';

const dynamicSizes = new Array(10000)
  .fill(true)
  .map(() => Math.round(Math.random() * 80 + 30));

export default function DynamicSizeVirtualList() {
  const instanceRef = useRef<VirtualizerInstance>(null);

  return (
    <div>
      <div className="demo-btns">
        <button
          onClick={() =>
            instanceRef.current?.scrollToIndex(3000, { align: 'center' })
          }
        >
          scrollToIndex(3000) with align center
        </button>
        <button onClick={() => instanceRef.current?.scrollToOffset(4000)}>
          scrollToOffset(4000)
        </button>
      </div>
      <VirtualList
        style={{ height: 400 }}
        itemClassName="demo-list-item"
        count={10000}
        dynamicSize
        overscan={2}
        size={60}
        onReady={(virtualizer) => {
          instanceRef.current = virtualizer;
        }}
      >
        {({ index }) => (
          <div
            style={{ height: dynamicSizes[index] }}
            className={index % 2 ? 'demo-list-odd' : 'demo-list-even'}
          >
            第 {index} 行
          </div>
        )}
      </VirtualList>
    </div>
  );
}
