// packages/taro/src/components/grid.tsx
import { VirtualListProps } from '../typings'
import { useVirualizer, useIsomorphicLayoutEffect } from '../hooks/use-virtualizer'
import { Fragment } from 'react'
import { ScrollView, View } from '@tarojs/components'
import {
  getRectSizeAsync,
  getScrollViewContextNode,
  getWindowRect,
  virtualizerUUID,
} from '../utils'
import Taro from '@tarojs/taro'
import type { MiniVirtualizer } from '@z-cloud/virtual-mini'

/**
 * grid 模式暂不支持动态尺寸
 * @param param0
 * @returns
 */
export function GridVirtualList({
  children,
  className,
  itemClassName,
  style,
  itemStyle,
  grid,
  gridSize,
  size,
  onReady,
  ...props
}: VirtualListProps) {
  const scrollId = `zcloud-virtual-list-${virtualizerUUID.value++}`
  const rowVirtualizer = useVirualizer({
    ...props,
    size: gridSize?.[1] ?? size,
    // 滚动模式只能竖向滚动
    horizontal: false,
  })

  const colVirtualizer = useVirualizer({ ...props, size: gridSize?.[0] ?? size, horizontal: true })

  const rowTotalSize = rowVirtualizer.getTotalSize()
  const colTotalSize = colVirtualizer.getTotalSize()

  const onScroll = (e: any) => {
    rowVirtualizer.onScroll(e.detail)
    colVirtualizer.onScroll(e.detail)
  }

  const init = async () => {
    const windowRect = getWindowRect()
    const elementRect = await getRectSizeAsync(scrollId)
    const scrollNode: any = await getScrollViewContextNode(scrollId)

    rowVirtualizer.setScrollElementRect(props.followPageScroll ? windowRect : elementRect)

    rowVirtualizer.scrollTo = function (this: MiniVirtualizer, offset, behavior) {
      if (!scrollNode) {
        console.warn('获取scrollNode失败')
        return
      }

      scrollNode.scrollTo({
        [this.options.horizontal ? 'left' : 'top']: offset,
        animated: props.dynamicSize ? false : behavior === 'smooth',
      })
    }

    if (props.followPageScroll) {
      rowVirtualizer.options.scrollMargin = elementRect.top ?? 0
      rowVirtualizer.scrollTo = (offset, behavior) => {
        Taro.pageScrollTo({
          scrollTop: offset,
          // 动态尺寸不支持滚动动画
          duration: behavior === 'smooth' && !props.dynamicSize ? 300 : 0,
        })
      }
    }

    colVirtualizer.setScrollElementRect(elementRect)
    colVirtualizer.scrollTo = rowVirtualizer.scrollTo ?? (() => {})
    rowVirtualizer.init()
    colVirtualizer.init()

    if (rowVirtualizer && colVirtualizer) {
      onReady?.(rowVirtualizer, colVirtualizer)
    }
  }

  useIsomorphicLayoutEffect(() => {
    init()

    return () => {
      rowVirtualizer.clean()
      colVirtualizer.clean()
    }
  }, [rowVirtualizer, colVirtualizer])

  return (
    <ScrollView
      scrollX
      scrollY
      enhanced
      className={className}
      style={{ overflow: 'auto', ...style }}
      id={scrollId}
      onScroll={onScroll}
    >
      <View
        style={{
          height: rowTotalSize,
          width: colTotalSize,
          display: 'grid',
          gridTemplateAreas: `"item"`,
        }}
      >
        {rowVirtualizer.getVirtualItems().map((rowItem) => (
          <Fragment key={rowItem.key}>
            {colVirtualizer.getVirtualItems().map((colItem) => (
              <View
                key={colItem.index}
                className={itemClassName}
                style={{
                  ...itemStyle,
                  gridArea: 'item',
                  height: rowItem.size,
                  width: colItem.size,
                  transform: `translate(${colItem.start}px,${rowItem.start}px)`,
                }}
              >
                {children(rowItem, colItem)}
              </View>
            ))}
          </Fragment>
        ))}
      </View>
    </ScrollView>
  )
}

// packages/vue/src/components/grid.vue
<script setup lang="ts">
import { computed, onMounted, ref, unref } from 'vue'
import { useVirualizer } from '../hooks/use-virtualizer'
import type { VirtualListProps } from '../typings'

const props = defineProps<VirtualListProps>()
const emit = defineEmits(['ready'])

const containerRef = ref<HTMLDivElement | null>(null)
const rowVirtualizerRef = useVirualizer(
  computed(() => ({ ...unref(props), size: props.gridSize?.[1] ?? props.size })),
  containerRef,
)
const colVirtualizerRef = useVirualizer(
  computed(() => ({ ...unref(props), size: props.gridSize?.[0] ?? props.size, horizontal: true })),
  containerRef,
)

const virtualItems = computed(() => {
  return [
    rowVirtualizerRef.value?.getVirtualItems() ?? [],
    colVirtualizerRef.value?.getVirtualItems() ?? [],
  ]
})

const totalSize = computed(() => {
  return [
    rowVirtualizerRef.value?.getTotalSize() ?? 0,
    colVirtualizerRef.value?.getTotalSize() ?? 0,
  ]
})

onMounted(() => {
  if (rowVirtualizerRef.value && colVirtualizerRef.value) {
    const scrollElement = props.followPageScroll ? window : containerRef.value!
    rowVirtualizerRef.value.init(scrollElement)
    colVirtualizerRef.value.init(scrollElement)
    emit('ready', rowVirtualizerRef.value, colVirtualizerRef.value)
  }
})
</script>

<template>
  <div style="overflow: auto" ref="containerRef">
    <div
      style="display: grid; grid-template-areas: 'item'"
      :style="{
        height: `${totalSize[0]}px`,
        width: `${totalSize[1]}px`,
      }"
    >
      <template v-for="rowItem in virtualItems[0]" :key="rowItem.index">
        <div
          v-for="colItem in virtualItems[1]"
          :key="colItem.index"
          :class="itemClassName"
          :style="{
            ...itemStyle,
            gridArea: 'item',
            height: `${rowItem.size}px`,
            width: `${colItem.size}px`,
            transform: `translate(${colItem.start}px,${rowItem.start}px)`,
          }"
        >
          <slot v-bind="rowItem" />
          <slot name="grid" :rowItem="rowItem" :colItem="colItem" />
        </div>
      </template>
    </div>
  </div>
</template>
